CFLAGS=-O0 -lpthread -lm

ALL=cartographer ram_bandwidth ram_access  

all: $(ALL)

#contentious: contentious.c contention.h

#contentious_setup: contentious_setup.c contention.h

#bw_client: bw_client.c bw.h

#bw_server: bw_server.c bw.h

clean: 
	rm -f *.o a.out $(ALL) *.pf *.bk
