CFLAGS=-O0 -lpthread -lm
ALL=bw_server bw_client client server client_RTT server_RTT

all: $(ALL)

#	gcc -o server_RTT server_RTT.c
#bw_client: bw_client.c bw.h

#bw_server: bw_server.c bw.h

clean: 
	rm -f *.o a.out $(ALL) *.pf *.bk
